# Generated by Django 4.1.3 on 2023-04-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/727/727399.png?w=740&t=st=1680948461~exp=1680949061~hmac=a6153e0bfcf0730e196145ccdc2e65f2bdfcac9326644563ff812bdf2b3fc0cd'),
        ),
    ]
